theme = "gruvbox"

[editor]
line-number = "relative"
cursorline = true
rulers = [80]
text-width = 80
bufferline = "always"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "register", "file-type"]
separator = "|"
mode.normal = "nor"
mode.insert = "ins"
mode.select = "sel"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1
